apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1-prod
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 4
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nanajanashia/argocd-app:1.1
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8080
