apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1-prod
spec:
  selector:
    app: app1
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
