apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1-staging
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nanajanashia/argocd-app:1.1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
