apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
spec:
  selector:
    matchLabels:
      app: apps
  replicas: 2
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
      - name: apps
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
