apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1-dev
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 2
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
