apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app1-prod

bases:
- ../../../base/app1

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app1
    spec:
      replicas: 4
      template:
        spec:
          containers:
          - name: app1
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 20
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: app1-service
    spec:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800
