apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: app2-prod
spec:
  selector:
    app: app2
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
