apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app2-staging

bases:
- ../../../base/app2

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app2
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: app2
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
