apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app1-dev

bases:
- ../../../base/app1

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app1
    spec:
      replicas: 2
