apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app2-dev

bases:
- ../../../base/app2

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app2
    spec:
      replicas: 2
